### ISSUE TITLE
Dataset for evaluating robustness

### ISSUE THREAD

**Issue by poppopbean0903** [OPTML-Group/UnlearnCanvas#8]
Can you explain how do you generate the dataset (including the prompts ) for each style/object? Can you provide the code for evaluating the robustness on object/style in unlearncanvas? Great thanks.

**Comment by NormalUhr** [comment]
Hi, please refer to our latest update on the README file (see [here](https://github.com/OPTML-Group/UnlearnCanvas/tree/master/machine_unlearning#update-on-codes-for-finer-scale-unlearning-robust-evaluation-and-sequential-unlearning)). We are sorry for any inconvenience this might cause.

**Comment by poppopbean0903** [comment]
Great thanks for your kind reply!  Would your consider providing the prompts used for both styles and objects robustness evaluations? I think maybe this should be consistent for following a benchmark and it would reduce much trouble of generating the prompts for users. It would be great gratitude if these prompts could be provided~
